wandb_api: "a0a43a4b820d0a581e3579b07d15bd9881f4b559"
train: True
pretrained: True
key: 0
num_seeds: 5
initial_seed: 3407
base_dir: "./numerical_results" # Directory where the experiment result is stored

# Data
path_dim: 4
n_lags: 100
logsig_level: 2
T: 0.1
data_dir: "./data/brownian" # For loading

# Model
algo: ["logsig_generator"]
datasets: ["brownian"]
gpu_id: "0"
device: "cuda"
use_cuda: True

# Generator
generator: "brownian"
G_input_dim: 32
G_hidden_dim: 32

# Discriminator
discriminator: "iid_gaussian_characteristic"
D_batch_size: 1000
D_hidden_dim: 32

# Trainer
train_batch_size: 512
lr_G: 0.001
lr_D: 0.001
train_num_steps: 10000
save_model: True
save_every: 1000
loss_track_every: 100
D_steps_per_G_step: 3
G_steps_per_D_step: 5
# results_folder: "./result/brownian" # For saving


# Tuning
method: "grid"
